services:
  storage:  
    image: minio/minio
    container_name: storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: fileconverter
      MINIO_ROOT_PASSWORD: DevPassword123!
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage_data:/data

  sqldb:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqldb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=DevPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqldb_data:/var/opt/mssql

  broker:
    image: rabbitmq:4-management
    container_name: broker
    hostname: broker
    environment:
      RABBITMQ_DEFAULT_USER: fileconverter
      RABBITMQ_DEFAULT_PASS: DevPassword123!
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - broker_data:/var/lib/rabbitmq

  converter-api:
    build:
      context: "./Api"
      dockerfile: Dockerfile
    container_name: converter-api
    ports:
      - "5194:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqldb;Database=FileConverter;User Id=sa;Password=DevPassword123!;TrustServerCertificate=True
      - Minio__Endpoint=storage:9000
      - Minio__AccessKey=admin
      - Minio__SecretKey=Password123!
    depends_on:
      - broker 
      - sqldb
      - storage

  converter-worker:
    build:
      context: "./Converter" 
    container_name: converter-worker
    environment:
      - BROKER_URL=
      - STORAGE_ENDPOINT=storage:9000
      - STORAGE_ACCESS_KEY=fileconverter
      - STORAGE_SECRET_KEY=DevPassword123!
      - STORAGE_BUCKET=user-files
    depends_on:
      broker:
        condition: service_healthy
      storage:
        condition: service_started

  frontend:
    build:
      context: "./Frontend"
      dockerfile: Dockerfile
    container_name: converter-frontend
    ports:
      - "3000:80"
    depends_on:
      - converter-api
  
volumes:
  broker_data:
  storage_data:
  sqldb_data: