// <auto-generated />
using System;
using Api.Shared.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(FileConverterContext))]
    [Migration("20260716145228_UpdateFileConverterModel")]
    partial class UpdateFileConverterModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Modules.Files.Infrastructure.Persistence.Entities.ConversionJobEntity", b =>
                {
                    b.Property<int>("ConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversionId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OutputFileId")
                        .HasColumnType("int");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("int");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ConversionId");

                    b.HasIndex("OutputFileId");

                    b.HasIndex("SourceFileId");

                    b.ToTable("Conversions", t =>
                        {
                            t.HasCheckConstraint("Chk_Conversions_Status", "\"Status\" IN ('Queued', 'Processing', 'Completed', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Api.Modules.Files.Infrastructure.Persistence.Entities.FileDataEntity", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FileId");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("Idx_Files_OwnerId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IdxUq_Files_PublicId");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("IdxUq_Files_StorageKey");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Api.Modules.Users.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PublicId")
                        .HasMaxLength(128)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IdxUq_Users_Email");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IdxUq_Users_PublicId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Modules.Files.Infrastructure.Persistence.Entities.ConversionJobEntity", b =>
                {
                    b.HasOne("Api.Modules.Files.Infrastructure.Persistence.Entities.FileDataEntity", null)
                        .WithMany()
                        .HasForeignKey("OutputFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Fk_OutputFileId_Files");

                    b.HasOne("Api.Modules.Files.Infrastructure.Persistence.Entities.FileDataEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Fk_SourceFileId_Files");
                });

            modelBuilder.Entity("Api.Modules.Files.Infrastructure.Persistence.Entities.FileDataEntity", b =>
                {
                    b.HasOne("Api.Modules.Users.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Fk_OwnerId_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
